# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Methodology',   url: 'methodology.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/GD-MRNG'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/glennlum/'}
- {icon: 'envelope',   link: 'mailto:glennlum@icloud.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

related_posts: 'Related:'
